import { User, Vendor, Product, PickupWindow, Order, Notification, Review, Coupon, FairLocation, VendorFairLocation } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-client-1',
    name: 'Maria Oliveira',
    email: 'maria.oliveira@email.com',
    phone: '(87) 99801-8279',
    whatsappPhone: '(87) 99801-8279',
    role: 'CLIENT',
  },
  {
    id: 'user-vendor-1',
    name: 'José Pereira (Zé dos Orgânicos)',
    email: 'ze.organicos@feirae.com',
    phone: '(87) 99801-8279',
    whatsappPhone: '(87) 99801-8279',
    role: 'VENDOR',
  },
  {
    id: 'user-vendor-2',
    name: 'Dona Neusa (Doces da Vovó)',
    email: 'neusa.doces@feirae.com',
    phone: '(87) 99801-8279',
    whatsappPhone: '(87) 99801-8279',
    role: 'VENDOR',
  },
  {
    id: 'user-vendor-3',
    name: 'Antônio Queijeiro (Serra da Canastra)',
    email: 'antonio.queijos@feirae.com',
    phone: '(87) 99801-8279',
    whatsappPhone: '(87) 99801-8279',
    role: 'VENDOR',
  },
  {
    id: 'user-admin-1',
    name: 'Administração Feira Livre Central',
    email: 'admin@feirae.com',
    phone: '(11) 3333-4444',
    whatsappPhone: '(87) 99801-8279',
    role: 'ADMIN',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    userId: 'user-vendor-1',
    businessName: 'Horta & Pomar do Zé',
    slug: 'horta-pomar-do-ze',
    description: 'Legumes, verduras e frutas 100% orgânicas colhidas na madrugada do dia da feira. Cultivo sustentável e sem agrotóxicos há mais de 15 anos.',
    category: 'Hortifrúti',
    fairLocation: 'Feira Livre da Praça da Matriz - Barraca 14',
    boothNumber: 'B-14',
    whatsappPhone: '(87) 99801-8279',
    coverImage: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=200&q=80',
    rating: 4.9,
    ratingCount: 38,
    isSubscriber: true,
    commissionRate: 0,
    isFeatured: true,
    featuredUntil: new Date(Date.now() + 86400000 * 14).toISOString(),
    featuredOrder: 1,
    active: true,
  },
  {
    id: 'vendor-2',
    userId: 'user-vendor-2',
    businessName: 'Delícias & Doces da Neusa',
    slug: 'delicias-doces-da-neusa',
    description: 'Compotas caseiras, geleias de frutas da época, pães artesanais de fermentação natural e bolos quentinhos feitos com receitas de família.',
    category: 'Doces & Panificação',
    fairLocation: 'Feira Livre da Praça da Matriz - Barraca 08',
    boothNumber: 'B-08',
    whatsappPhone: '(87) 99801-8279',
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?auto=format&fit=crop&w=200&q=80',
    rating: 4.8,
    ratingCount: 29,
    isSubscriber: false,
    commissionRate: 0.05,
    isFeatured: false,
    active: true,
  },
  {
    id: 'vendor-3',
    userId: 'user-vendor-3',
    businessName: 'Queijaria Artesanal da Serra',
    slug: 'queijaria-artesanal-da-serra',
    description: 'Queijos meia cura, curados, frescais, manteiga de garrafa e doces de leite artesanais trazidos diretamente de pequenos produtores de Minas.',
    category: 'Queijos & Laticínios',
    fairLocation: 'Feira Livre da Praça da Matriz - Barraca 22',
    boothNumber: 'B-22',
    whatsappPhone: '(87) 99801-8279',
    coverImage: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 5.0,
    ratingCount: 45,
    isSubscriber: true,
    commissionRate: 0,
    isFeatured: true,
    featuredUntil: new Date(Date.now() + 86400000 * 7).toISOString(),
    featuredOrder: 2,
    active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Vendor 1
  {
    id: 'prod-1',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    name: 'Alface Crespa Orgânica (Maço)',
    description: 'Alface crespa fresca, colhida no dia, crocante e sem agrotóxicos.',
    category: 'Hortaliças',
    unit: 'maço',
    price: 4.50,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
    isOrganic: true,
    isActive: true,
  },
  {
    id: 'prod-2',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    name: 'Tomate Italiano Orgânico',
    description: 'Tomates maduros selecionados, ideais para molhos ou saladas frescas.',
    category: 'Legumes',
    unit: 'kg',
    price: 8.90,
    stock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    isOrganic: true,
    isWeighable: true,
    isActive: true,
  },
  {
    id: 'prod-3',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    name: 'Cenoura com Rama Orgânica',
    description: 'Cenouras doces e crocantes com ramas verdes cheias de nutrientes.',
    category: 'Legumes',
    unit: 'kg',
    price: 6.50,
    stock: 12,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80',
    isOrganic: true,
    isWeighable: true,
    isActive: true,
  },
  {
    id: 'prod-4',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    name: 'Morangos Selecionados (Bandeja 300g)',
    description: 'Morangos super doces e aromáticos, direto da estufa orgânica.',
    category: 'Frutas',
    unit: 'bandeja',
    price: 12.00,
    stock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    isOrganic: true,
    isActive: true,
  },

  // Vendor 2
  {
    id: 'prod-5',
    vendorId: 'vendor-2',
    vendorName: 'Delícias & Doces da Neusa',
    name: 'Pão Rústico de Fermentação Natural',
    description: 'Pão de casca crocante e miolo macio aerado, fermentação lenta de 36 horas.',
    category: 'Panificação',
    unit: 'unid',
    price: 18.00,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isActive: true,
  },
  {
    id: 'prod-6',
    vendorId: 'vendor-2',
    vendorName: 'Delícias & Doces da Neusa',
    name: 'Geleia Artesanal de Jabuticaba (250g)',
    description: 'Geleia 100% natural feita com frutas frescas do sítio e pouco açúcar.',
    category: 'Doces & Geleias',
    unit: 'pote',
    price: 16.50,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1597528662465-55ece5734101?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isActive: true,
  },
  {
    id: 'prod-7',
    vendorId: 'vendor-2',
    vendorName: 'Delícias & Doces da Neusa',
    name: 'Bolo Caseiro de Fubá Cremoso com Goiabada',
    description: 'Bolo quentinho, macio e com pedaços generosos de goiabada cascão.',
    category: 'Bolos & Doces',
    unit: 'unid',
    price: 22.00,
    stock: 6,
    imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isActive: true,
  },

  // Vendor 3
  {
    id: 'prod-8',
    vendorId: 'vendor-3',
    vendorName: 'Queijaria Artesanal da Serra',
    name: 'Queijo Meia Cura Canastra (Cerca de 600g)',
    description: 'Autêntico queijo artesanal da Canastra, maturação de 21 dias, sabor marcante.',
    category: 'Queijos',
    unit: 'peça',
    price: 38.00,
    stock: 14,
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isWeighable: true,
    isActive: true,
  },
  {
    id: 'prod-9',
    vendorId: 'vendor-3',
    vendorName: 'Queijaria Artesanal da Serra',
    name: 'Manteiga de Garrafa Tradicional (500ml)',
    description: 'Manteiga clarificada artesanal com aroma inconfundível.',
    category: 'Laticínios',
    unit: 'garrafa',
    price: 24.00,
    stock: 9,
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isActive: true,
  },
  {
    id: 'prod-10',
    vendorId: 'vendor-3',
    vendorName: 'Queijaria Artesanal da Serra',
    name: 'Doce de Leite Cremoso com Favo de Baunilha (400g)',
    description: 'Feito no tacho de cobre com leite fresco da fazenda e baixo teor de açúcar.',
    category: 'Doces de Leite',
    unit: 'pote',
    price: 19.50,
    stock: 16,
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
    isOrganic: false,
    isActive: true,
  }
];

export const INITIAL_PICKUP_WINDOWS: PickupWindow[] = [
  {
    id: 'pw-1',
    vendorId: 'vendor-1',
    fairLocationId: 'fair-1',
    dayOfWeek: 'Sábado',
    startTime: '07:30',
    endTime: '09:30',
    location: 'Barraca 14 - Praça da Matriz',
    maxOrders: 20,
    active: true,
  },
  {
    id: 'pw-2',
    vendorId: 'vendor-1',
    fairLocationId: 'fair-1',
    dayOfWeek: 'Sábado',
    startTime: '09:30',
    endTime: '11:30',
    location: 'Barraca 14 - Praça da Matriz',
    maxOrders: 20,
    active: true,
  },
  {
    id: 'pw-1b',
    vendorId: 'vendor-1',
    fairLocationId: 'fair-2',
    dayOfWeek: 'Quarta-feira',
    startTime: '16:00',
    endTime: '18:30',
    location: 'Barraca 08 - Feira do Bairro Novo',
    maxOrders: 25,
    active: true,
  },
  {
    id: 'pw-3',
    vendorId: 'vendor-2',
    fairLocationId: 'fair-1',
    dayOfWeek: 'Sábado',
    startTime: '08:00',
    endTime: '10:00',
    location: 'Barraca 08 - Praça da Matriz',
    maxOrders: 15,
    active: true,
  },
  {
    id: 'pw-4',
    vendorId: 'vendor-3',
    fairLocationId: 'fair-1',
    dayOfWeek: 'Sábado',
    startTime: '08:00',
    endTime: '11:00',
    location: 'Barraca 22 - Praça da Matriz',
    maxOrders: 25,
    active: true,
  },
  {
    id: 'pw-4b',
    vendorId: 'vendor-3',
    fairLocationId: 'fair-3',
    dayOfWeek: 'Domingo',
    startTime: '07:30',
    endTime: '11:30',
    location: 'Barraca 03 - Parque Josepha Coelho',
    maxOrders: 20,
    active: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'FL-2026-001',
    clientId: 'user-client-1',
    clientName: 'Maria Oliveira',
    clientPhone: '(11) 98765-4321',
    clientEmail: 'maria.oliveira@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 22.30,
    status: 'NOVO',
    paymentMethod: 'RETIRADA',
    paymentStatus: 'PAGO_NA_RETIRADA',
    pickupDate: 'Próximo Sábado (29/08)',
    pickupLocation: 'Barraca 14 - Praça da Matriz (07:30 - 09:30)',
    notes: 'Por favor, selecionar alface bem viçosa.',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    items: [
      {
        id: 'item-1',
        orderId: 'order-1',
        productId: 'prod-1',
        productName: 'Alface Crespa Orgânica (Maço)',
        productUnit: 'maço',
        unitPrice: 4.50,
        quantity: 2,
        subtotal: 9.00,
      },
      {
        id: 'item-2',
        orderId: 'order-1',
        productId: 'prod-2',
        productName: 'Tomate Italiano Orgânico',
        productUnit: 'kg',
        unitPrice: 8.90,
        quantity: 1,
        measuredWeight: null,
        subtotal: 8.90,
      },
      {
        id: 'item-3',
        orderId: 'order-1',
        productId: 'prod-3',
        productName: 'Cenoura com Rama Orgânica',
        productUnit: 'kg',
        unitPrice: 6.50,
        quantity: 1,
        measuredWeight: null,
        subtotal: 6.50,
      }
    ],
  },
  {
    id: 'order-2',
    orderNumber: 'FL-2026-002',
    clientId: 'user-client-1',
    clientName: 'Maria Oliveira',
    clientPhone: '(11) 98765-4321',
    clientEmail: 'maria.oliveira@email.com',
    vendorId: 'vendor-3',
    vendorName: 'Queijaria Artesanal da Serra',
    totalAmount: 38.00,
    status: 'PRONTO',
    paymentMethod: 'MERCADO_PAGO_PIX',
    paymentStatus: 'SIMULADO_APROVADO',
    mpPaymentId: 'MP-SANDBOX-9837192',
    pickupDate: 'Próximo Sábado (29/08)',
    pickupLocation: 'Barraca 22 - Praça da Matriz (08:00 - 11:00)',
    notes: 'Vou retirar por volta das 09h.',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    items: [
      {
        id: 'item-4',
        orderId: 'order-2',
        productId: 'prod-8',
        productName: 'Queijo Meia Cura Canastra (Cerca de 600g)',
        productUnit: 'peça',
        unitPrice: 38.00,
        quantity: 1,
        subtotal: 38.00,
      }
    ],
  },
  {
    id: 'order-3',
    orderNumber: 'FL-2026-003',
    clientId: 'user-client-1',
    clientName: 'Maria Oliveira',
    clientPhone: '(11) 98765-4321',
    clientEmail: 'maria.oliveira@email.com',
    vendorId: 'vendor-2',
    vendorName: 'Delícias & Doces da Neusa',
    totalAmount: 34.50,
    status: 'RETIRADO',
    paymentMethod: 'RETIRADA',
    paymentStatus: 'PAGO_NA_RETIRADA',
    pickupDate: 'Sábado Passado',
    pickupLocation: 'Barraca 08 - Praça da Matriz',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    items: [
      {
        id: 'item-5',
        orderId: 'order-3',
        productId: 'prod-5',
        productName: 'Pão Rústico de Fermentação Natural',
        productUnit: 'unid',
        unitPrice: 18.00,
        quantity: 1,
        subtotal: 18.00,
      },
      {
        id: 'item-6',
        orderId: 'order-3',
        productId: 'prod-6',
        productName: 'Geleia Artesanal de Jabuticaba (250g)',
        productUnit: 'pote',
        unitPrice: 16.50,
        quantity: 1,
        subtotal: 16.50,
      }
    ],
    review: {
      id: 'rev-1',
      orderId: 'order-3',
      vendorId: 'vendor-2',
      clientId: 'user-client-1',
      clientName: 'Maria Oliveira',
      rating: 5,
      comment: 'O pão estava maravilhoso e a geleia super fresca! Retirada muito rápida na barraca.',
      vendorReply: 'Muito obrigada, Maria! Preparamos tudo com muito amor na véspera da feira. Te esperamos no próximo sábado!',
      vendorReplyAt: new Date(Date.now() - 3600000 * 36).toISOString(),
      createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
    }
  },
  {
    id: 'order-4',
    orderNumber: 'FL-2026-004',
    clientId: 'user-client-1',
    clientName: 'Carlos Eduardo Mendes',
    clientPhone: '(87) 99123-4567',
    clientEmail: 'carlos.mendes@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 52.00,
    status: 'RETIRADO',
    paymentMethod: 'MERCADO_PAGO_PIX',
    paymentStatus: 'SIMULADO_APROVADO',
    mpPaymentId: 'MP-SANDBOX-1029384',
    pickupDate: '05/09/2026',
    pickupLocation: 'Barraca 14 - Praça da Matriz',
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    items: [
      {
        id: 'item-7',
        orderId: 'order-4',
        productId: 'prod-1',
        productName: 'Alface Crespa Orgânica (Maço)',
        productUnit: 'maço',
        unitPrice: 4.50,
        quantity: 4,
        subtotal: 18.00,
      },
      {
        id: 'item-8',
        orderId: 'order-4',
        productId: 'prod-2',
        productName: 'Tomate Italiano Orgânico',
        productUnit: 'kg',
        unitPrice: 8.90,
        quantity: 2,
        subtotal: 17.80,
      },
      {
        id: 'item-9',
        orderId: 'order-4',
        productId: 'prod-4',
        productName: 'Morango Orgânico Selecionado (Caixa 300g)',
        productUnit: 'caixa',
        unitPrice: 16.20,
        quantity: 1,
        subtotal: 16.20,
      }
    ],
  },
  {
    id: 'order-5',
    orderNumber: 'FL-2026-005',
    clientId: 'user-client-1',
    clientName: 'Ana Paula Silveira',
    clientPhone: '(87) 98877-6655',
    clientEmail: 'ana.silveira@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 43.50,
    status: 'RETIRADO',
    paymentMethod: 'RETIRADA',
    paymentStatus: 'PAGO_NA_RETIRADA',
    pickupDate: '29/08/2026',
    pickupLocation: 'Barraca 14 - Praça da Matriz',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    items: [
      {
        id: 'item-10',
        orderId: 'order-5',
        productId: 'prod-1',
        productName: 'Alface Crespa Orgânica (Maço)',
        productUnit: 'maço',
        unitPrice: 4.50,
        quantity: 3,
        subtotal: 13.50,
      },
      {
        id: 'item-11',
        orderId: 'order-5',
        productId: 'prod-3',
        productName: 'Cenoura com Rama Orgânica',
        productUnit: 'kg',
        unitPrice: 6.50,
        quantity: 2,
        subtotal: 13.00,
      },
      {
        id: 'item-12',
        orderId: 'order-5',
        productId: 'prod-4',
        productName: 'Morango Orgânico Selecionado (Caixa 300g)',
        productUnit: 'caixa',
        unitPrice: 17.00,
        quantity: 1,
        subtotal: 17.00,
      }
    ],
  },
  {
    id: 'order-6',
    orderNumber: 'FL-2026-006',
    clientId: 'user-client-1',
    clientName: 'Roberto Albuquerque',
    clientPhone: '(87) 97766-5544',
    clientEmail: 'roberto.albuquerque@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 67.80,
    status: 'RETIRADO',
    paymentMethod: 'MERCADO_PAGO_CARTAO',
    paymentStatus: 'SIMULADO_APROVADO',
    mpPaymentId: 'MP-SANDBOX-8761234',
    pickupDate: '22/08/2026',
    pickupLocation: 'Barraca 14 - Praça da Matriz',
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    items: [
      {
        id: 'item-13',
        orderId: 'order-6',
        productId: 'prod-2',
        productName: 'Tomate Italiano Orgânico',
        productUnit: 'kg',
        unitPrice: 8.90,
        quantity: 4,
        subtotal: 35.60,
      },
      {
        id: 'item-14',
        orderId: 'order-6',
        productId: 'prod-4',
        productName: 'Morango Orgânico Selecionado (Caixa 300g)',
        productUnit: 'caixa',
        unitPrice: 16.10,
        quantity: 2,
        subtotal: 32.20,
      }
    ],
  },
  {
    id: 'order-7',
    orderNumber: 'FL-2026-007',
    clientId: 'user-client-1',
    clientName: 'Juliana Costa',
    clientPhone: '(87) 99654-3211',
    clientEmail: 'juliana.costa@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 38.50,
    status: 'RETIRADO',
    paymentMethod: 'RETIRADA',
    paymentStatus: 'PAGO_NA_RETIRADA',
    pickupDate: '15/08/2026',
    pickupLocation: 'Barraca 14 - Praça da Matriz',
    createdAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    items: [
      {
        id: 'item-15',
        orderId: 'order-7',
        productId: 'prod-1',
        productName: 'Alface Crespa Orgânica (Maço)',
        productUnit: 'maço',
        unitPrice: 4.50,
        quantity: 3,
        subtotal: 13.50,
      },
      {
        id: 'item-16',
        orderId: 'order-7',
        productId: 'prod-3',
        productName: 'Cenoura com Rama Orgânica',
        productUnit: 'kg',
        unitPrice: 6.50,
        quantity: 2,
        subtotal: 13.00,
      },
      {
        id: 'item-17',
        orderId: 'order-7',
        productId: 'prod-2',
        productName: 'Tomate Italiano Orgânico',
        productUnit: 'kg',
        unitPrice: 6.00,
        quantity: 2,
        subtotal: 12.00,
      }
    ],
  },
  {
    id: 'order-8',
    orderNumber: 'FL-2026-008',
    clientId: 'user-client-1',
    clientName: 'Mariana Fontes',
    clientPhone: '(87) 98111-2233',
    clientEmail: 'mariana.fontes@email.com',
    vendorId: 'vendor-1',
    vendorName: 'Horta & Pomar do Zé',
    totalAmount: 31.50,
    status: 'RETIRADO',
    paymentMethod: 'RETIRADA',
    paymentStatus: 'PAGO_NA_RETIRADA',
    pickupDate: '05/09/2026',
    pickupLocation: 'Barraca 14 - Praça da Matriz',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    items: [
      {
        id: 'item-18',
        orderId: 'order-8',
        productId: 'prod-1',
        productName: 'Alface Crespa Orgânica (Maço)',
        productUnit: 'maço',
        unitPrice: 4.50,
        quantity: 3,
        subtotal: 13.50,
      },
      {
        id: 'item-19',
        orderId: 'order-8',
        productId: 'prod-3',
        productName: 'Cenoura com Rama Orgânica',
        productUnit: 'kg',
        unitPrice: 6.50,
        quantity: 2,
        subtotal: 13.00,
      },
      {
        id: 'item-20',
        orderId: 'order-8',
        productId: 'prod-1',
        productName: 'Rúcula Fresca Orgânica',
        productUnit: 'maço',
        unitPrice: 5.00,
        quantity: 1,
        subtotal: 5.00,
      }
    ],
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    orderId: 'order-3',
    vendorId: 'vendor-2',
    clientId: 'user-client-1',
    clientName: 'Maria Oliveira',
    rating: 5,
    comment: 'O pão estava maravilhoso e a geleia super fresca! Retirada muito rápida na barraca.',
    vendorReply: 'Muito obrigada, Maria! Preparamos tudo com muito amor na véspera da feira. Te esperamos no próximo sábado!',
    vendorReplyAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
  },
  {
    id: 'rev-2',
    orderId: 'order-past-2',
    vendorId: 'vendor-1',
    clientId: 'user-client-2',
    clientName: 'Carlos Eduardo',
    rating: 5,
    comment: 'Verduras sempre fresquinhas e crocantes. O pré-pedido me poupou de pegar fila na feira.',
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: 'rev-3',
    orderId: 'order-past-3',
    vendorId: 'vendor-3',
    clientId: 'user-client-3',
    clientName: 'Ana Beatriz',
    rating: 5,
    comment: 'O melhor queijo Canastra da região! Atendimento nota 10.',
    createdAt: new Date(Date.now() - 3600000 * 96).toISOString(),
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-client-1',
    title: 'Pedido Pronto para Retirada!',
    message: 'Seu pré-pedido #FL-2026-002 na Queijaria Artesanal da Serra já está embalado e aguardando sua retirada.',
    type: 'ORDER_STATUS',
    orderId: 'order-2',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-vendor-1',
    title: 'Novo Pré-pedido Recebido!',
    message: 'Maria Oliveira fez um novo pré-pedido (#FL-2026-001) no valor de R$ 22,30.',
    type: 'NEW_ORDER',
    orderId: 'order-1',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'FEIRA10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 20.00,
    maxUses: 100,
    usedCount: 5,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'coup-2',
    code: 'FEIRA5',
    discountType: 'FIXED',
    discountValue: 5.00,
    minOrderValue: 15.00,
    maxUses: 50,
    usedCount: 2,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'coup-3',
    code: 'EXPIRADO10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 0,
    maxUses: 10,
    usedCount: 0,
    expiresAt: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 dias atrás
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'coup-4',
    code: 'ESGOTADO5',
    discountType: 'FIXED',
    discountValue: 5.00,
    minOrderValue: 10.00,
    maxUses: 3,
    usedCount: 3, // esgotado
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_FAIRS: FairLocation[] = [
  {
    id: 'fair-1',
    name: 'Feira Livre da Praça da Matriz',
    slug: 'praca-da-matriz',
    address: 'Praça da Matriz, Centro Histórico',
    city: 'Petrolina - PE',
    schedule: 'Sábados, 06:30 às 12:30',
    operatingDays: 'Sábado',
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'fair-2',
    name: 'Feira Livre do Bairro Novo',
    slug: 'bairro-novo',
    address: 'Av. das Nações, em frente ao Mercado Comunitário',
    city: 'Petrolina - PE',
    schedule: 'Quartas-feiras, 15:00 às 20:30',
    operatingDays: 'Quarta-feira',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'fair-3',
    name: 'Feira Agroecológica do Parque',
    slug: 'agroecologica-parque',
    address: 'Parque Municipal Josepha Coelho',
    city: 'Petrolina - PE',
    schedule: 'Domingos, 07:00 às 12:00',
    operatingDays: 'Domingo',
    imageUrl: 'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
];

export const INITIAL_VENDOR_FAIRS: VendorFairLocation[] = [
  // Vendor 1 (Zé dos Orgânicos) - Praça da Matriz (Sábado) & Bairro Novo (Quarta)
  {
    id: 'vf-1',
    vendorId: 'vendor-1',
    fairLocationId: 'fair-1',
    boothNumber: 'Barraca 14',
    assignedDays: 'Sábado',
    active: true,
  },
  {
    id: 'vf-2',
    vendorId: 'vendor-1',
    fairLocationId: 'fair-2',
    boothNumber: 'Barraca 08',
    assignedDays: 'Quarta-feira',
    active: true,
  },
  // Vendor 2 (Dona Neusa) - Praça da Matriz (Sábado)
  {
    id: 'vf-3',
    vendorId: 'vendor-2',
    fairLocationId: 'fair-1',
    boothNumber: 'Barraca 08',
    assignedDays: 'Sábado',
    active: true,
  },
  // Vendor 3 (Queijaria Canastra) - Praça da Matriz (Sábado) & Parque (Domingo)
  {
    id: 'vf-4',
    vendorId: 'vendor-3',
    fairLocationId: 'fair-1',
    boothNumber: 'Barraca 22',
    assignedDays: 'Sábado',
    active: true,
  },
  {
    id: 'vf-5',
    vendorId: 'vendor-3',
    fairLocationId: 'fair-3',
    boothNumber: 'Barraca 03',
    assignedDays: 'Domingo',
    active: true,
  },
];

